/**
 * Barrel: JSON slide contract types + runtime parser.
 * Prefer importing from here for backward compatibility; new code may import from
 * `jsonSlideTypes` / `parseJsonSlideDocument` directly.
 */

export type {
  JsonSlideTextStack,
  JsonSlideTextStackAlign,
  JsonSlideTextStackDocument,
  JsonSlideTextStackItem,
  JsonSlideTextStackItemContext,
  JsonSlideTextStackItemLink,
  JsonSlideTextStackItemSize,
  JsonSlideTextStackItemText,
  JsonSlideTextStackItemVariant,
  JsonSlideTextStackJustify,
  JsonSlideTextStackReveal,
  JsonSlideTextStackRevealPreset,
  JsonSlideAsymmetricLayout,
  JsonSlideBackdrop,
  JsonSlideBackdropVariant,
  JsonSlideBentoItem,
  JsonSlideBentoLayout,
  JsonSlideCard,
  JsonSlideCardComponentId,
  JsonSlideCardHeaderBadge,
  JsonSlideCardIconId,
  JsonSlideCardItem,
  JsonSlideCardItemIndexedList,
  JsonSlideCardItemTagList,
  JsonSlideCardItemText,
  JsonSlideCardItemVariant,
  JsonSlideCardHeaderBadgeTone,
  JsonSlideCardSurface,
  JsonSlideCardTagListDirection,
  JsonSlideCardTagListVariant,
  JsonSlideCardJustify,
  JsonSlideCardPadding,
  JsonSlideCardSubtitle,
  JsonSlideCardTone,
  JsonSlideColumnItem,
  JsonSlideContent,
  JsonSlideContentAlign,
  JsonSlideContentDensity,
  JsonSlideContentWidth,
  JsonImageCover,
  JsonImageCoverBackground,
  JsonSlideDefaultDocument,
  JsonSlideDocument,
  JsonSlideImageCoverDocument,
  JsonSlideEqualLayout,
  JsonSlideFrame,
  JsonSlideFrameAlign,
  JsonSlideFramePadding,
  JsonSlideGridGap,
  JsonSlideHeader,
  JsonSlideHeaderAlign,
  JsonSlideLayout,
  JsonSlideMediaGalleryCellVariant,
  JsonSlideMediaGalleryItem,
  JsonSlideMediaGalleryItemImage,
  JsonSlideMediaGalleryItemVideo,
  JsonSlideMediaGalleryLayout,
  JsonSlideMediaGalleryObjectAlign,
  JsonSlideMediaGalleryObjectFit,
  JsonSlideMediaGalleryVerticalAlign,
  JsonSlideRegion,
  JsonSlideSplitLayout,
  JsonSlideStackItem,
  JsonSlideStackLayout,
  JsonSlideTextRegionAlign,
  JsonSlideTextRegionPayload,
  JsonSlideUniformGridLayout,
} from './jsonSlideTypes';

export {
  isJsonSlideImageCoverDocument,
  isJsonSlideTextStackDocument,
  isJsonSlideCardItemIndexedList,
  isJsonSlideCardItemTagList,
  isJsonSlideCardItemText,
  JSON_SLIDE_CARD_COMPONENT_IDS,
  JSON_SLIDE_CARD_ICON_IDS,
} from './jsonSlideTypes';

export type { ParseJsonSlideResult } from './parseJsonSlideDocument';
export { parseJsonSlideDocument } from './parseJsonSlideDocument';
