/** IDs for JSON and demo slides in the main deck (`/`), aligned with `decks/main/schemas/`. */
export const DEMO_JSON_SLIDE_IDS = {
  asymmetric: 'demo-json-grid-asymmetric',
  equal: 'demo-json-grid-equal',
  bento: 'demo-json-grid-bento',
  heroJourneyBento: 'demo-hero-journey-bento',
} as const;

export const MIGRATED_JSON_SLIDE_IDS = {
  platformsEcosystem: 'platforms-ecosystem-bento',
  attentionModels2026: 'attention-models-2026',
  nanoBananaUseCases: 'nano-banana-use-cases',
  midjourneyVsNanoBanana: 'midjourney-vs-nano-banana',
  promptStructure: 'prompt-structure',
  editingPromptStructure: 'editing-prompt-structure',
  higgsfield: 'higgsfield',
  nodeBasedSystems: 'node-based-systems',
  flouxDemo: 'floux-demo',
  agenticWorkflowResult: 'agentic-workflow-result',
  agenticWorkflow: 'agentic-workflow',
  promptOrderPairImages: 'prompt-order-pair-images',
  editingPromptPrinciples: 'editing-prompt-principles',
  referenceRoles: 'reference-roles',
  leoWideShot: 'leo-wide-shot',
  styleCopyPromptPrinciples: 'style-copy-prompt-principles',
  styleCopyPromptPrinciplesCopy2: 'style-copy-prompt-principles-copy-2',
  styleCopyPromptPrinciplesCopy3: 'style-copy-prompt-principles-copy-3',
  styleCopyPromptPrinciplesCopy4: 'style-copy-prompt-principles-copy-4',
  nanoBananaProCover: 'nano-banana-pro',
  multiReferenceCover: 'multi-reference',
  texturingModelingCover: 'texturing-modeling-cover',
  jsonPromptingCover: 'json-prompting-cover',
  referenceAnalysis: 'reference-analysis',
  anglesLighting: 'angles-lighting',
  photorealismModelPicks: 'photorealism-model-picks',
  aboutMe: 'about-me',
  proContradictions: 'pro-contradictions',
  lessObviousUseCases: 'less-obvious-use-cases',
  photorealismSectionTitle: 'photorealism-section-title',
  nanoBananaConnection: 'nano-banana-connection',
  lessObviousSectionTitle: 'less-obvious-section-title',
  threeDWorkflowLink: 'three-d-workflow-link',
  compositionPhotoLink: 'composition-photo-link',
  grokImagineBento: 'grok-imagine-bento',
  recraftV4Bento: 'recraft-v4-bento',
  midjorneyBento: 'midjorney-bento',
  jsonImagesTriptych: 'json-images-triptych',
  textureWorkflow: 'texture-workflow',
  threeDTwoRefsTwoOuts: '3d-two-refs-two-outs',
  workflowComparison: 'workflow-comparison',
  otherExamplesFlouxProjects: 'other-examples-floux-projects',
  promptOrderFlex: 'prompt-order-flex',
  nanoBananaVersions: 'nano-banana-versions',
} as const;
