import type { DeckDefinition } from '../types';
import { JsonSlideRenderer } from '../json-renderer/JsonSlideRenderer';
import { VIBECODING_DECK_SLIDE_IDS } from './vibecodingSlideIds';

export const vibecodingDeck: DeckDefinition = {
  id: 'vibecoding',
  title: 'Вайбкодинг',
  defaultSlideId: VIBECODING_DECK_SLIDE_IDS.cover,
  slides: [
    {
      id: VIBECODING_DECK_SLIDE_IDS.cover,
      title: 'Вайбкодинг',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт I · Пролог. История одной трансформации — от идеи до задеплоенного продукта.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.definition,
      title: 'Обычный мир',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт I · Обычный мир и зов. Фрустрация «идея есть — рук нет», момент освобождения (Масад).',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.refusal,
      title: 'Отказ от зова',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт I · Отказ от зова. Три страха на пороге: интеллектуальный, самозванец, техскепсис.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.cycle,
      title: 'Встреча с наставником',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт I · Наставник и переход порога. Первый промпт — барьер между идеей и реальностью рушится.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.landscape,
      title: 'Мир приключений',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт II · Мир приключений. Карта дорог вайбкодинга 2026 — пять категорий.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.platforms,
      title: 'Проводники',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт II · Проводники. Replit, Lovable, Bolt — три ставки для новичка.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.philosophies,
      title: 'Развилка',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт II · Развилка. Закрытая платформа против открытой разработки — две тропы.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.proTools,
      title: 'Оружие мастера',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт II · Оружие мастера. Cursor и Claude Code — индустриальный стандарт pro-уровня.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.cursorVsClaude,
      title: 'Два наставника',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт II · Два наставника. Характеры Cursor и Claude Code — выбор зависит от того, кем ты становишься.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.doomLoop,
      title: 'Главное испытание',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Главное испытание. Трёхголовый дракон: техдолг, когнитивный долг, архитектурная энтропия.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.costOfReliability,
      title: 'Цена надёжности',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Цена надёжности. ×2–4, когнитивный долг, от Accept All к критическому ревью.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.architecture,
      title: 'Артефакт силы I',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Артефакт силы I — архитектура. Слои Data/Controller/View как границы против энтропии.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.rules,
      title: 'Артефакт силы II',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Артефакт силы II — правила. CLAUDE.md, .cursorrules, AGENTS.md как постоянный контекст.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.mcp,
      title: 'Артефакт силы III',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Артефакт силы III — MCP. Чувства агента во внешнем мире: БД, доки, SDK.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.subagents,
      title: 'Артефакт силы IV',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Артефакт силы IV — субагенты. Союзники-делегаты: тесты, доки, ревью параллельно.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.security,
      title: 'Последний удар',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Последний удар испытания. 70% уязвимых: RLS, вебхуки, инъекции — цена игнора hardening.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.closing,
      title: 'Возвращение с эликсиром',
      theme: 'editorial',
      component: JsonSlideRenderer,
      notes: 'Акт III · Возвращение с эликсиром. Дизайнер-директор систем — идеи в продукт за недели.',
    },
    {
      id: VIBECODING_DECK_SLIDE_IDS.demo,
      title: 'Демо: старт',
      theme: 'editorial',
      component: JsonSlideRenderer,
      hidden: true,
      notes: 'Старая заготовка; оставлена скрытой для совместимости.',
    },
  ],
};
