/**
 * Slide ids для вайбкодинг-деки (`/vibecoding`).
 *
 * Сценарий — `vibecoding-deck-plan.md`. Legacy-ключи прежней версии лежат в
 * `./vibecoding/archive/legacyVibecodingSlideIds.ts` (`VIBECODING_LEGACY_SLIDE_IDS`).
 * Префикс `v2` отделяет новые id от архивных (`vibecoding-01-cover` и т.д.).
 */
export const VIBECODING_DECK_SLIDE_IDS = {
  cover: 'vibecoding-v2-01-cover',
  aboutMe: 'vibecoding-v2-01a-about-me',
  why: 'vibecoding-v2-01b-why',
  pastTeam: 'vibecoding-v2-02-past-team',
  nowSoloAi: 'vibecoding-v2-03-now-solo-ai',
  shiftIsReal: 'vibecoding-v2-04-shift-is-real',
  booster: 'vibecoding-v2-05-booster',
  futureRole: 'vibecoding-v2-05b-future-role',
  outcomesLadder: 'vibecoding-v2-05c-outcomes',
  hero: 'vibecoding-v2-06-hero',
  threeFears: 'vibecoding-v2-07-three-fears',
  act2Separator: 'vibecoding-v2-08-act2-separator',
  landscape: 'vibecoding-v2-09-landscape',
  sandboxes: 'vibecoding-v2-10-sandboxes',
  agentVsChat: 'vibecoding-v2-11-agent-vs-chat',
  constructorVsAgent: 'vibecoding-v2-12-constructor-vs-agent',
  cursorVsClaude: 'vibecoding-v2-13-cursor-vs-claude',
  pricing: 'vibecoding-v2-14-pricing',
  cursorForDesigners: 'vibecoding-v2-15-cursor-for-designers',
  claudeIdeEntry: 'vibecoding-v2-16-claude-ide-entry',
  localSetup: 'vibecoding-v2-16b-local-setup',
  act3Separator: 'vibecoding-v2-17-act3-separator',
  iterationsNotMagic: 'vibecoding-v2-18-iterations-not-magic',
  valleyOfDespair: 'vibecoding-v2-19-valley-of-despair',
  contextWindow: 'vibecoding-v2-19-context-window',
  summarization: 'vibecoding-v2-20-summarization',
  contextDrift: 'vibecoding-v2-21-context-drift',
  mdMemory: 'vibecoding-v2-22-md-memory',
  act4Separator: 'vibecoding-v2-23-act4-separator',
  rulesPredictable: 'vibecoding-v2-24-rules-predictable',
  rulesExample1: 'vibecoding-v2-25-rules-example-1',
  rulesExample2: 'vibecoding-v2-26-rules-example-2',
  skills: 'vibecoding-v2-27-skills',
  subagents: 'vibecoding-v2-28-subagents',
  allySetup: 'vibecoding-v2-28b-ally-setup',
  mcp: 'vibecoding-v2-29-mcp',
  agentModes: 'vibecoding-v2-29b-agent-modes',
  act5Separator: 'vibecoding-v2-30-act5-separator',
  scalingChallenge: 'vibecoding-v2-31-scaling-challenge',
  doomLoop: 'vibecoding-v2-32-doom-loop',
  basicsMatter: 'vibecoding-v2-33-basics-matter',
  costOfReliability: 'vibecoding-v2-34-cost-of-reliability',
  securityHoles: 'vibecoding-v2-35-security-holes',
  act6Separator: 'vibecoding-v2-36-act6-separator',
  orchestration: 'vibecoding-v2-37-orchestration',
} as const;
